apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: dev
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30004
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 30003
  selector:
    app: rabbitmq
  type: NodePort
