apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.10.1
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/pipeline/
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
            items:
              - key: logstash.conf
                path: logstash.conf
