apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: dev
spec:
  selector:
    app: elasticsearch
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
      nodePort: 30005
  type: NodePort
