apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: dev
spec:
  selector:
    app: logstash
  ports:
    - name: logstash
      port: 5044
      targetPort: 5044
      nodePort: 30011
  type: NodePort
