apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: dev
spec:
  selector:
    app: kibana
  ports:
    - name: kibana
      port: 5601
      targetPort: 5601
      nodePort: 30006
  type: NodePort
