apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: dev
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30010
  type: NodePort
