apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: dev
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 30002
  selector:
    app: redis
  sessionAffinity: None
  type: NodePort
